services:
    web:
        image: 'caddy:alpine'
        container_name: web
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./:/var/www/html
          - ./caddy/Caddyfile:/etc/caddy/Caddyfile
          - caddy_data:/data
          - caddy_config:/config
        networks:
          - example-net
        depends_on:
          - app  
        links:
          - app
        restart: unless-stopped    
    
    app:
        build:
            dockerfile: Dockerfile
        volumes:
          - ./:/var/www/html
          - ./php/php.ini:/usr/local/etc/php/php.ini
        networks:
          - example-net
        restart: unless-stopped
        tty: true
        # depends_on:
        #   - db
    db:
        image: mysql:8.0
        volumes: 
          - mysqldata:/var/lib/mysql
        ports:
          - "3308:3306"
        networks:
          - example-net
        restart: unless-stopped
        command: ['--max_allowed_packet=325058560', '--local-infile=1', '--loose-local-infile=1']
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: results
    
    # phpmyadmin:
    #     image: phpmyadmin
    #     container_name: phpmyadmin
    #     restart: always
    #     ports:
    #       - 5147:80
    #     environment:
    #         PMA_HOST: db
    #         MYSQL_ROOT_PASSWORD: 12345678
    #         UPLOAD_LIMIT: 10G
    #     depends_on:
    #       - db
    #     networks:
    #       - example-net

volumes:
    caddy_data:
    caddy_config:
    mysqldata:

networks:
  example-net:
    driver: bridge
    name: example-net